In [90]:
from sklearn.linear_model import LinearRegression
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error,root_mean_squared_error

In [91]:
file_path=r"C:\Users\muham\Downloads\kc_house_data.csv\kc_house_data.csv"
df=pd.read_csv(file_path)

In [92]:
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [93]:
df=df.drop(columns=['id','date'])

In [94]:
df.corr()['price'].sort_values()

zipcode         -0.053203
long             0.021626
condition        0.036362
yr_built         0.054012
sqft_lot15       0.082447
sqft_lot         0.089661
yr_renovated     0.126434
floors           0.256794
waterfront       0.266369
lat              0.307003
bedrooms         0.308350
sqft_basement    0.323816
view             0.397293
bathrooms        0.525138
sqft_living15    0.585379
sqft_above       0.605567
grade            0.667434
sqft_living      0.702035
price            1.000000
Name: price, dtype: float64

In [95]:
feature=['bedrooms','bathrooms','sqft_living','sqft_lot','floors','waterfront','view']
X=df[feature]

In [96]:
X

       bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view
0             3       1.00         1180      5650     1.0           0     0
1             3       2.25         2570      7242     2.0           0     0
2             2       1.00          770     10000     1.0           0     0
3             4       3.00         1960      5000     1.0           0     0
4             3       2.00         1680      8080     1.0           0     0
...         ...        ...          ...       ...     ...         ...   ...
21608         3       2.50         1530      1131     3.0           0     0
21609         4       2.50         2310      5813     2.0           0     0
21610         2       0.75         1020      1350     2.0           0     0
21611         3       2.50         1600      2388     2.0           0     0
21612         2       0.75         1020      1076     2.0           0     0

[21613 rows x 7 columns]

In [97]:
Y=df['price']

In [98]:
Y

0        221900.0
1        538000.0
2        180000.0
3        604000.0
4        510000.0
           ...
21608    360000.0
21609    400000.0
21610    402101.0
21611    400000.0
21612    325000.0
Name: price, Length: 21613, dtype: float64

In [99]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [100]:
model=LinearRegression()

In [101]:
model.fit(X_train,Y_train)

LinearRegression()

In [102]:
prediction=model.predict(X_test)
prediction

array([ 494620.21086195,  681665.89232842, 1121212.22817448, ...,
        600584.21373896,  531932.55022195,  635738.34982212],
      shape=(4323,))

In [103]:
r2_score(Y_test,prediction)

0.5680120617944369

In [104]:
mean_squared_error(Y_test,prediction)

65306516232.535164

In [105]:
mean_absolute_error(Y_test,prediction)

166487.4386260057

In [106]:
root_mean_squared_error(Y_test,prediction)

255551.39645976337

In [107]:
model.coef_

array([-4.50680212e+04,  9.30070407e+03,  2.79689654e+02, -4.07699261e-01,
        7.88609174e+03,  5.26276896e+05,  7.48049139e+04])

In [108]:
model.intercept_

np.float64(62861.61373567232)